# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'connect-api' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for connect-api
  pod 'Alamofire', '~>5.1'

end
